# Generated by Django 6.0.5 on 2026-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_images/'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/donation_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/event_images/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='media/gallery/'),
        ),
    ]
