# Generated by Django 6.0.5 on 2026-06-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
    ]
