# Generated by Django 6.0.5 on 2026-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_payment_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month_covered',
            field=models.CharField(blank=True, help_text='Month this payment covers (e.g., July 2026)', max_length=50, null=True),
        ),
    ]
